title: The Pond
author: VEESCREAMS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Listen to the croaks of the little frogs, and songs of our little friends!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
